# ================================
# PDF config (can overwrite main config.yaml)
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
# ================================

# add some input files
input-files:
  - ./src/appendix.md

log-file: build/pdf.log
output-file: build/index.pdf
pdf-engine: xelatex # wkhtmltopdf, weasyprint, prince, pdflatex, lualatex, xelatex, latexmk, pdfroff, context, tectonic
to: pdf
toc-depth: 3
toc: false
