# ================================
# Tex config (can overwrite main config.yaml)
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
# ================================
#
# add some input files
input-files:
  - ./src/appendix/appendix.md

log-file: build/tex.log
output-file: build/index.tex
to: latex

toc-depth: 3
