# ================================
# HTML config (can overwrite main config.yaml)
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
# ================================


# add some input files
input-files:
  #- ./src/appendix.md

# styling
css:
  - ./config/html/css/main.css
  - ./config/html/css/print.css
  - ./config/html/css/font_tufte.css
  #- ./config/html/css/font_poppins.css
  #- ./config/html/css/font_merriweather.css

# output
log-file: build/html.log
output-file: build/index.html
to: html
