# ================================
# HTML config (can overwrite main config.yaml)
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
# ================================


# add some input files
input-files:
  - ./src/appendix.md

# styling
css:
  - ./config/html/css/main.css          # use :root here for easy customization
  - ./config/html/css/print.css         # print to pdf styling
  - ./config/html/css/font_tufte.css    # font-related
  # different font-styles (uncomment):
  #- ./config/html/css/font_poppins.css
  #- ./config/html/css/font_merriweather.css

# output
log-file: build/html.log
output-file: build/index.html
to: html
