# ================================
# HTML config and layout
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
# ================================

filters:
  - pandoc-crossref
 #- src/filters/multiple-bibliographies.lua # comment out for quick build (no refs)
  #- src/filters/pandoc-quotes.lua
input-files:
  - ./src/_base.md
  - ./src/abstract.md
  #- ./src/01_intro.md
  - ./src/02_chapter_1.md
  - ./src/03_conclusion.md
  - ./src/04_acknowledgment.md
  - ./src/05_references.md
  - ./src/appendix.md
  #- ./src/list_of_tables.md
  #- ./src/list_of_figures.md
  #- ./src/list_of_listings.md
css:
  - ./config/html/css/tufte.css
  - ./config/html/css/print.css
log-file: build/html.log
output-file: build/index.html
to: html
toc-depth: 3
listings: true
