# ==================
# Pandoc base config
# ==================
#
# https://pandoc.org/MANUAL.html#options-affecting-specific-writers
# NOTE:
# All options can be overwritten in the file-specific ./config/<fmt>/layout.yaml

cite-method: citeproc # citeproc, natbib, or biblatex
#citeproc: true
embed-resources: true
file-scope: false # Parse each file individually before combining for multifile documents. This will allow footnotes in different files with the same identifiers to work as expected. If this option is set, footnotes and links will not work across files.
from: markdown
highlight-style: pygments
reference-location: block # block, section, or document
resource-path:
  - ${.}/../
  - ${.}/../src
  - ${.}/
standalone: true
top-level-division: default # part, chapter, section, or default
toc: true
number-sections: true
verbosity: WARNING # ERROR, WARNING, or INFO

# MORE: output-specific configs (and outline) found in subdirs
