# =========================================================================
# Pandoc main config
#
# Notes:
#   - <https://pandoc.org/MANUAL.html#general-writer-options-1>
#   - <https://pandoc.org/MANUAL.html#options-affecting-specific-writers>
#   - metadata (and other configs) is set in `src/_base.md`
#   - all options can be overwritten in file-specific './config/<fmt>/config.yaml'
#     (for `input-files`, file-specific additions are possible, but not a full
#     overwrite)
# =========================================================================

from: markdown
verbosity: WARNING # ERROR, WARNING, or INFO

filters:
  - pandoc-crossref
  - src/filters/multiple-bibliographies.lua # comment out for quick build (no refs)
  #- src/filters/pandoc-quotes.lua

# -------------------------------------------------------------------------
# Layout
# -------------------------------------------------------------------------

# you can extend the input-files in the output-specific configs
input-files:
  - ./src/_base.md
  - ./src/abstract.md
  - ./src/01_intro.md
  - ./src/02_chapter_1.md
  - ./src/03_conclusion.md
  - ./src/04_acknowledgment.md
  - ./src/05_references.md
  #- ./src/appendix.md # add this per outpuf file (see ./<format>/config.yaml)

# -------------------------------------------------------------------------

cite-method: citeproc # citeproc, natbib, or biblatex
embed-resources: true
file-scope: false # Parse each file individually before combining for multifile
                  # documents. This will allow footnotes in different files with
                  # the same identifiers to work as expected. If this option is
                  # set, footnotes and links will not work across files.
highlight-style: pygments
reference-location: block # block, section, or document
resource-path:
  - ${.}/../
  - ${.}/../assets/img
  - ${.}/../src
  - ${.}/
standalone: false
top-level-division: default # part, chapter, section, or default
toc: true
listings: true
number-sections: true
toc-depth: 3
